function Jacfvar = Jacobian_Jun13T1_III(A,B1,B2,mu,epsilonu,...
    cf,cp,beta,phi,delta,sigma,lambda,b,r,pstar,...
    epsilond,epsilonc,theta,alpha)
%JACOBIAN_JUN13_III
%    JACFVAR = JACOBIAN_JUN13_III(A,B1,B2,MU,EPSILONU,CF,CP,BETA,PHI,DELTA,SIGMA,LAMBDA,B,R,PSTAR,EPSILOND,EPSILONC,THETA,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Jun-2017 16:35:03

%{
F = [part11-part12,part21-part22,part31 - part32,part41-part42];

var=[epsilond,epsilonc,theta,alpha,...
    pstar,b,phi,sigma,beta,...
    lambda,cf,r,cp,delta];
% [1,14]

Jacfvar = jacobian(F,var);
% jacobian matrix
% [4,14]
% [dF1_dx1,...dF1_dxN,
%  
%  dFN_dx1,.....dFN_dxN]
%}
syms x
t2 = 1.0./B2;
t3 = theta.^t2;
t4 = t3.^(-B1);
t5 = A.*t4.*theta;
t6 = lambda+r+t5;
t7 = 1.0./sigma;
t8 = -x+1.0;
t9 = log(t8);
t10 = t9.*8.493218002880191e-1;
t11 = t10+2.943525056288687e-1;
t12 = erf(t11);
t13 = t12.*(1.0./2.0);
t14 = t13+1.0./2.0;

t17 = int(t14,x,epsilond,epsilonu);
t18 = 1.0./t6;
t19 = 1.0./t6.^2;
t20 = -epsilonc+1.0;
t21 = log(t20);
t22 = t21.*8.493218002880191e-1;
t23 = t22+2.943525056288687e-1;
t24 = erf(t23);
t25 = t24.*(1.0./2.0);
t26 = t25+1.0./2.0;
t27 = phi-1.0;
t28 = 1.0./t27;
t40 = phi.*t26;
t29 = lambda+r-t40;
t30 = beta-1.0;
t31 = 1.0./t30;
t32 = A.*t4;
t33 = t2-1.0;
t34 = theta.^t33;
t35 = -B1-1.0;
t36 = t3.^t35;
t38 = A.*B1.*t2.*t34.*t36.*theta;
t37 = t32-t38;
t39 = epsilonc-epsilond;
t41 = 1.0./delta;
t45 = phi.*t30;
t42 = beta-t45;
t43 = delta-1.0;
t44 = alpha-1.0;
t46 = 1.0./t27.^2;
t47 = 1.0./t30.^2;
t50 = int(t14,x,epsilonc,epsilonu);
t51 = lambda+r;
t52 = 1.0./t51;
t53 = 1.0./t51.^2;
t54 = delta.*lambda.*t19;
t55 = delta.*t18.*t28.*t39;
t56 = alpha.*beta.*cp.*t31;
t57 = cf.*t28.*t31.*t42.*t44;
t58 = t56+t57;
t59 = b-pstar;
t60 = 1.0./cf;
t61 = epsilonc-epsilonu;
t62 = sigma.*t52.*t61;
t63 = delta.*sigma.*t18.*t28.*t39;
t64 = t62+t63;
t65 = sigma.*t53.*t61;
t66 = delta.*sigma.*t19.*t28.*t39;
t67 = t65+t66;
t68 = 1.0./A;
t69 = B1-1.0;
t70 = t3.^t69;
t71 = B1.*t2.*t34.*t68.*t70;
t72 = 1.0./cp;
t73 = epsilond-epsilonu;
t74 = delta.*sigma.*t19.*t30.*t72.*t73;
Jacfvar = reshape([-lambda.*t18.*(erf(log(-epsilond+1.0).*8.493218002880191e-1+2.943525056288687e-1).*(1.0./2.0)+1.0./2.0)+1.0,-delta-delta.*t18.*t28.*t29,-delta.*sigma.*t18.*t30.*t60,-delta.*sigma.*t18.*t30.*t72,0.0,-t26.*(lambda.*t52-delta.*lambda.*t18)+delta.*t18.*t28.*t29-(delta.*phi.*t18.*t28.*t39.*1.0./sqrt(pi).*exp(-t23.^2).*8.493218002880191e-1)./(epsilonc-1.0)+1.0,t27.*t30.*t60.*(sigma.*t52+delta.*sigma.*t18.*t28),0.0,-lambda.*t17.*t19.*t37,t41.*t58+delta.*lambda.*t19.*t37.*t50-delta.*t19.*t28.*t29.*t37.*t39,t71-delta.*sigma.*t19.*t30.*t37.*t39.*t60,t71+delta.*sigma.*t19.*t30.*t37.*t72.*t73,0.0,t41.*theta.*(beta.*cp.*t31+cf.*t28.*t31.*t42),0.0,0.0,t7,-t41.*t43,0.0,0.0,-t7,t41.*t43,0.0,0.0,0.0,-t41.*theta.*(cf.*t28.*t44+cf.*t31.*t42.*t44.*t46)-delta.*t18.*t26.*t28.*t39-delta.*t18.*t29.*t39.*t46,t30.*t60.*t64-delta.*sigma.*t18.*t28.*t30.*t39.*t60,0.0,1.0./sigma.^2.*t59,0.0,t27.*t30.*t60.*(t55+t52.*t61),-delta.*t18.*t30.*t72.*t73,0.0,-t41.*theta.*(-alpha.*cp.*t31+cf.*t31.*t44+alpha.*beta.*cp.*t47+cf.*t28.*t42.*t44.*t47),t27.*t60.*t64,-delta.*sigma.*t18.*t72.*t73,t17.*t18-lambda.*t17.*t19,t55+t50.*(t52+t54-delta.*t18-lambda.*t53)-delta.*t19.*t28.*t29.*t39,-t27.*t30.*t60.*t67,t74,0.0,t28.*t31.*t41.*t42.*t44.*theta,-1.0./cf.^2.*t27.*t30.*t64,0.0,-lambda.*t17.*t19,t55+t50.*(t54-lambda.*t53)-delta.*t19.*t28.*t29.*t39,-t27.*t30.*t60.*t67,t74,0.0,alpha.*beta.*t31.*t41.*theta,0.0,1.0./cp.^2.*delta.*sigma.*t18.*t30.*t73,0.0,-epsilond-1.0./delta.^2.*(t43.*t59+t58.*theta)+t41.*t59-lambda.*t18.*t50+t18.*t28.*t29.*t39,sigma.*t18.*t30.*t39.*t60,-sigma.*t18.*t30.*t72.*t73],[4,14]);
