% Symbolic Jun 13, 2017
% May 22, 2017
function [DELTAF_pms,DELTAF_ps,DELTAF_pps]...
    = fun_DELTAF(epsilon,epsilonc_pms,epsilonc_ps,epsilonc_pps,...
    epsilond_pms,epsilond_ps,epsilond_pps,...
    tau_pms,tau_ps,tau_pps,...
    r,lambda,g_p,mu,delta)



[DELTAP_pms,DELTAP_ps,DELTAP_pps] = fun_DELTAP(epsilon,...
    epsilond_pms,epsilond_ps,epsilond_pps,...
    tau_pms,tau_ps,tau_pps,g_p,mu);


DELTAF_ps = fun_DELTAF_ps_1(r,lambda,mu)*...
    heaviside(epsilon-epsilonc_pms)+...
    fun_DELTAF_ps_2(r,lambda,mu,g_p,delta,DELTAP_pms)*...
    heaviside(epsilon-epsilonc_ps)*...
    (1-heaviside(epsilon-epsilonc_pms))+...
    delta*DELTAP_ps*...
    heaviside(epsilon-epsilonc_pps)*...
    (1-heaviside(epsilon-epsilonc_ps))+...
    delta*DELTAP_ps*...
    (1-heaviside(epsilon-epsilonc_pps));

DELTAF_pms = (1+mu*DELTAF_ps)/(r+lambda+mu)*...
    heaviside(epsilon-epsilonc_pms)+...
    delta*DELTAP_pms*...
    heaviside(epsilon-epsilonc_ps)*...
    (1-heaviside(epsilon-epsilonc_pms))+...
    delta*DELTAP_pms*...
    heaviside(epsilon-epsilonc_pps)*...
    (1-heaviside(epsilon-epsilonc_ps))+...
    delta*DELTAP_pms*...
    (1-heaviside(epsilon-epsilonc_pps));

DELTAF_pps = DELTAF_pms*...
    heaviside(epsilon-epsilonc_pms)+...
    (1+mu*DELTAF_ps)/(r+lambda+mu)*...
    heaviside(epsilon-epsilonc_ps)*...
    (1-heaviside(epsilon-epsilonc_pms))+...
    (1+mu*DELTAF_ps)/(r+lambda+mu)*...
    heaviside(epsilon-epsilonc_pps)*...
    (1-heaviside(epsilon-epsilonc_ps))+...
    delta*DELTAP_pps*...
    (1-heaviside(epsilon-epsilonc_pps));
    

return