dF_dbeta=[0,(-1).*\[Delta].^(-1).*\[Theta].*(cF.*(1+(-1).*\[Alpha]).*(1+(-1).*\[Beta]) ...
  .^(-1)+cP.*\[Alpha].*(1+(-1).*\[Beta]).^(-1)+cP.*\[Alpha].*(1+(-1).*\[Beta]) ...
  .^(-2).*\[Beta]+cF.*(1+(-1).*\[Alpha]).*(1+(-1).*\[Beta]).^(-2).*(1+( ...
  -1).*\[Phi]).^(-1).*(\[Beta]+(1+(-1).*\[Beta]).*\[Phi])),cF.^(-1).*((( ...
  -1).*\[Epsilon]c+\[Epsilon]u).*(r+\[Lambda]).^(-1).*\[Sigma]+\[Delta].*(\[Epsilon]c+(-1).*\[Epsilon]d).*(r+ ...
  A.*\[Theta].^(1+(-1).*B)+\[Lambda]).^(-1).*\[Sigma].*(1+(-1).*\[Phi]).^(-1)) ...
  .*(1+(-1).*\[Phi]),cP.^(-1).*\[Delta].*((-1).*\[Epsilon]d+\[Epsilon]u).*(r+A.* ...
  \[Theta].^(1+(-1).*B)+\[Lambda]).^(-1).*\[Sigma]];
