dF_dcp=[0,(-1).*\[Alpha].*(1+(-1).*\[Beta]).^(-1).*\[Beta].*\[Delta].^(-1).*\[Theta],0, ...
  cP.^(-2).*(1+(-1).*\[Beta]).*\[Delta].*((-1).*\[Epsilon]d+\[Epsilon]u).*(r+A.* ...
  \[Theta].^(1+(-1).*B)+\[Lambda]).^(-1).*\[Sigma]];
