dF_dsigma=[(b+(-1).*pstar).*\[Sigma].^(-2),0,(-1).*cF.^(-1).*(1+( ...
  -1).*\[Beta]).*(((-1).*\[Epsilon]c+\[Epsilon]u).*(r+\[Lambda]).^(-1)+\[Delta].*(\[Epsilon]c+(-1).* ...
  \[Epsilon]d).*(r+A.*\[Theta].^(1+(-1).*B)+\[Lambda]).^(-1).*(1+(-1).*\[Phi]).^( ...
  -1)).*(1+(-1).*\[Phi]),(-1).*cP.^(-1).*(1+(-1).*\[Beta]).*\[Delta].* ...
  ((-1).*\[Epsilon]d+\[Epsilon]u).*(r+A.*\[Theta].^(1+(-1).*B)+\[Lambda]).^(-1)];
