% symbolic Jun 13, 2017
% May 22, 2017
function [DELTAP_pms,DELTAP_ps,DELTAP_pps]...
    = fun_DELTAP(epsilon,epsilond_pms,epsilond_ps,epsilond_pps,...
    tau_pms,tau_ps,tau_pps,g_p,mu)



DELTAP_pms = fun_DELTAP_pms_1(tau_pms,tau_ps,tau_pps,g_p,mu)*...
    heaviside(epsilon-epsilond_pms);

DELTAP_ps = (tau_pms*DELTAP_pms-1)/mu*...
    heaviside(epsilon-epsilond_pms)+...
    fun_DELTAP_ps_2(tau_pms,tau_ps,tau_pps,g_p,mu)*...
    heaviside(epsilon-epsilond_ps)*...
    (1-heaviside(epsilon-epsilond_pms));

DELTAP_pps = tau_pms*DELTAP_pms/tau_pps*...
    heaviside(epsilon-epsilond_pms)+...
    (1+mu*DELTAP_ps)/tau_pps*...
    heaviside(epsilon-epsilond_ps)*...
    (1-heaviside(epsilon-epsilond_pms))+...
    (1/tau_pps)*...
    heaviside(epsilon-epsilond_pps)*...
    (1-heaviside(epsilon-epsilond_ps));
    

return