% May 22, 2017
function DELTAP_pps...
    = fun_DELTAP_pps(epsilon,epsilond_pms,epsilond_ps,...
    epsilond_pps,tau_pms,tau_ps,tau_pps,g_p,mu)

[~,~,DELTAP_pps]...
    = fun_DELTAP(epsilon,epsilond_pms,epsilond_ps,...
    epsilond_pps,tau_pms,tau_ps,tau_pps,g_p,mu);

return